apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfg-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mfg-site
  template:
    metadata:
      labels:
        app: mfg-site
    spec:
      containers:
        - name: web
          image: vinaysunhare/manufacturing-site:v2
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mfg-site-svc
spec:
  type: LoadBalancer
  selector:
    app: mfg-site
  ports:
    - port: 80
      targetPort: 80
