apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manufacturing-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vinaysunhare/gitops-with-argo-cd.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
